<?php

use Illuminate\Database\Seeder;

class StocksTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('stocks')->delete();
        
        \DB::table('stocks')->insert(array (
            0 => 
            array (
                'id' => 1,
                'variation_id' => 1,
                'total_stock' => 2,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:20:14',
                'updated_at' => '2021-04-20 20:20:14',
            ),
            1 => 
            array (
                'id' => 2,
                'variation_id' => 2,
                'total_stock' => 16,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:20:24',
                'updated_at' => '2021-04-20 20:20:24',
            ),
            2 => 
            array (
                'id' => 3,
                'variation_id' => 3,
                'total_stock' => 8,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 2,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:20:27',
                'updated_at' => '2021-04-20 20:20:27',
            ),
            3 => 
            array (
                'id' => 4,
                'variation_id' => 4,
                'total_stock' => 3,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 3,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:20:31',
                'updated_at' => '2021-04-20 20:20:31',
            ),
            4 => 
            array (
                'id' => 5,
                'variation_id' => 5,
                'total_stock' => 5,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 1,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:20:34',
                'updated_at' => '2021-04-20 20:20:34',
            ),
            5 => 
            array (
                'id' => 6,
                'variation_id' => 6,
                'total_stock' => 5,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:20:34',
                'updated_at' => '2021-04-20 20:20:34',
            ),
            6 => 
            array (
                'id' => 7,
                'variation_id' => 7,
                'total_stock' => 3,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:20:37',
                'updated_at' => '2021-04-20 20:20:37',
            ),
            7 => 
            array (
                'id' => 8,
                'variation_id' => 8,
                'total_stock' => 6,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:20:41',
                'updated_at' => '2021-04-20 20:20:41',
            ),
            8 => 
            array (
                'id' => 9,
                'variation_id' => 9,
                'total_stock' => 6,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:20:41',
                'updated_at' => '2021-04-20 20:20:41',
            ),
            9 => 
            array (
                'id' => 10,
                'variation_id' => 10,
                'total_stock' => 3,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:20:43',
                'updated_at' => '2021-04-20 20:20:43',
            ),
            10 => 
            array (
                'id' => 11,
                'variation_id' => 11,
                'total_stock' => 12,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 1,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:20:46',
                'updated_at' => '2021-04-20 20:20:46',
            ),
            11 => 
            array (
                'id' => 12,
                'variation_id' => 12,
                'total_stock' => 12,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:20:46',
                'updated_at' => '2021-04-20 20:20:46',
            ),
            12 => 
            array (
                'id' => 13,
                'variation_id' => 13,
                'total_stock' => 2,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 2,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:20:52',
                'updated_at' => '2021-04-20 20:20:52',
            ),
            13 => 
            array (
                'id' => 14,
                'variation_id' => 14,
                'total_stock' => 3,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 1,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:20:55',
                'updated_at' => '2021-04-20 20:20:55',
            ),
            14 => 
            array (
                'id' => 15,
                'variation_id' => 15,
                'total_stock' => 4,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:20:58',
                'updated_at' => '2021-04-20 20:20:58',
            ),
            15 => 
            array (
                'id' => 16,
                'variation_id' => 16,
                'total_stock' => 4,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:20:58',
                'updated_at' => '2021-04-20 20:20:58',
            ),
            16 => 
            array (
                'id' => 17,
                'variation_id' => 17,
                'total_stock' => 2,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:21:01',
                'updated_at' => '2021-04-20 20:21:01',
            ),
            17 => 
            array (
                'id' => 18,
                'variation_id' => 18,
                'total_stock' => 4,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:21:04',
                'updated_at' => '2021-04-20 20:21:04',
            ),
            18 => 
            array (
                'id' => 19,
                'variation_id' => 19,
                'total_stock' => 4,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:21:04',
                'updated_at' => '2021-04-20 20:21:04',
            ),
            19 => 
            array (
                'id' => 20,
                'variation_id' => 20,
                'total_stock' => 2,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:21:11',
                'updated_at' => '2021-04-20 20:21:11',
            ),
            20 => 
            array (
                'id' => 21,
                'variation_id' => 21,
                'total_stock' => 9,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 3,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:21:14',
                'updated_at' => '2021-04-20 20:21:14',
            ),
            21 => 
            array (
                'id' => 22,
                'variation_id' => 22,
                'total_stock' => 2,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:21:24',
                'updated_at' => '2021-04-20 20:21:24',
            ),
            22 => 
            array (
                'id' => 23,
                'variation_id' => 23,
                'total_stock' => 10,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:21:27',
                'updated_at' => '2021-04-20 20:21:27',
            ),
            23 => 
            array (
                'id' => 24,
                'variation_id' => 24,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:21:31',
                'updated_at' => '2021-04-20 20:21:31',
            ),
            24 => 
            array (
                'id' => 25,
                'variation_id' => 25,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:21:34',
                'updated_at' => '2021-04-20 20:21:34',
            ),
            25 => 
            array (
                'id' => 26,
                'variation_id' => 26,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:21:34',
                'updated_at' => '2021-04-20 20:21:34',
            ),
            26 => 
            array (
                'id' => 27,
                'variation_id' => 27,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:21:37',
                'updated_at' => '2021-04-20 20:21:37',
            ),
            27 => 
            array (
                'id' => 28,
                'variation_id' => 28,
                'total_stock' => 11,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:21:41',
                'updated_at' => '2021-04-20 20:21:41',
            ),
            28 => 
            array (
                'id' => 29,
                'variation_id' => 29,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:21:44',
                'updated_at' => '2021-04-20 20:21:44',
            ),
            29 => 
            array (
                'id' => 30,
                'variation_id' => 30,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:21:51',
                'updated_at' => '2021-04-20 20:21:51',
            ),
            30 => 
            array (
                'id' => 31,
                'variation_id' => 31,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:21:54',
                'updated_at' => '2021-04-20 20:21:54',
            ),
            31 => 
            array (
                'id' => 32,
                'variation_id' => 32,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:21:54',
                'updated_at' => '2021-04-20 20:21:54',
            ),
            32 => 
            array (
                'id' => 33,
                'variation_id' => 33,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:21:57',
                'updated_at' => '2021-04-20 20:21:57',
            ),
            33 => 
            array (
                'id' => 34,
                'variation_id' => 34,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:22:01',
                'updated_at' => '2021-04-20 20:22:01',
            ),
            34 => 
            array (
                'id' => 35,
                'variation_id' => 35,
                'total_stock' => 3,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:22:03',
                'updated_at' => '2021-04-20 20:22:03',
            ),
            35 => 
            array (
                'id' => 36,
                'variation_id' => 36,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:22:06',
                'updated_at' => '2021-04-20 20:22:06',
            ),
            36 => 
            array (
                'id' => 37,
                'variation_id' => 37,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:22:10',
                'updated_at' => '2021-04-20 20:22:10',
            ),
            37 => 
            array (
                'id' => 38,
                'variation_id' => 38,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:22:12',
                'updated_at' => '2021-04-20 20:22:12',
            ),
            38 => 
            array (
                'id' => 39,
                'variation_id' => 39,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:22:12',
                'updated_at' => '2021-04-20 20:22:12',
            ),
            39 => 
            array (
                'id' => 40,
                'variation_id' => 40,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:22:15',
                'updated_at' => '2021-04-20 20:22:15',
            ),
            40 => 
            array (
                'id' => 41,
                'variation_id' => 41,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:22:18',
                'updated_at' => '2021-04-20 20:22:18',
            ),
            41 => 
            array (
                'id' => 42,
                'variation_id' => 42,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:22:21',
                'updated_at' => '2021-04-20 20:22:21',
            ),
            42 => 
            array (
                'id' => 43,
                'variation_id' => 43,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:22:24',
                'updated_at' => '2021-04-20 20:22:24',
            ),
            43 => 
            array (
                'id' => 44,
                'variation_id' => 44,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:22:24',
                'updated_at' => '2021-04-20 20:22:24',
            ),
            44 => 
            array (
                'id' => 45,
                'variation_id' => 45,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:22:32',
                'updated_at' => '2021-04-20 20:22:32',
            ),
            45 => 
            array (
                'id' => 46,
                'variation_id' => 46,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:22:32',
                'updated_at' => '2021-04-20 20:22:32',
            ),
            46 => 
            array (
                'id' => 47,
                'variation_id' => 47,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:22:34',
                'updated_at' => '2021-04-20 20:22:34',
            ),
            47 => 
            array (
                'id' => 48,
                'variation_id' => 48,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:22:34',
                'updated_at' => '2021-04-20 20:22:34',
            ),
            48 => 
            array (
                'id' => 49,
                'variation_id' => 49,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:22:41',
                'updated_at' => '2021-04-20 20:22:41',
            ),
            49 => 
            array (
                'id' => 50,
                'variation_id' => 50,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:22:45',
                'updated_at' => '2021-04-20 20:22:45',
            ),
            50 => 
            array (
                'id' => 51,
                'variation_id' => 51,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:22:48',
                'updated_at' => '2021-04-20 20:22:48',
            ),
            51 => 
            array (
                'id' => 52,
                'variation_id' => 52,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:22:50',
                'updated_at' => '2021-04-20 20:22:50',
            ),
            52 => 
            array (
                'id' => 53,
                'variation_id' => 53,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:22:50',
                'updated_at' => '2021-04-20 20:22:50',
            ),
            53 => 
            array (
                'id' => 54,
                'variation_id' => 54,
                'total_stock' => 6,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:22:54',
                'updated_at' => '2021-04-20 20:22:54',
            ),
            54 => 
            array (
                'id' => 55,
                'variation_id' => 55,
                'total_stock' => 6,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:22:57',
                'updated_at' => '2021-04-20 20:22:57',
            ),
            55 => 
            array (
                'id' => 56,
                'variation_id' => 56,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:23:00',
                'updated_at' => '2021-04-20 20:23:00',
            ),
            56 => 
            array (
                'id' => 57,
                'variation_id' => 57,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:23:03',
                'updated_at' => '2021-04-20 20:23:03',
            ),
            57 => 
            array (
                'id' => 58,
                'variation_id' => 58,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:23:06',
                'updated_at' => '2021-04-20 20:23:06',
            ),
            58 => 
            array (
                'id' => 59,
                'variation_id' => 59,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:23:10',
                'updated_at' => '2021-04-20 20:23:10',
            ),
            59 => 
            array (
                'id' => 60,
                'variation_id' => 60,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:23:13',
                'updated_at' => '2021-04-20 20:23:13',
            ),
            60 => 
            array (
                'id' => 61,
                'variation_id' => 61,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:23:16',
                'updated_at' => '2021-04-20 20:23:16',
            ),
            61 => 
            array (
                'id' => 62,
                'variation_id' => 62,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:23:20',
                'updated_at' => '2021-04-20 20:23:20',
            ),
            62 => 
            array (
                'id' => 63,
                'variation_id' => 63,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:23:22',
                'updated_at' => '2021-04-20 20:23:22',
            ),
            63 => 
            array (
                'id' => 64,
                'variation_id' => 64,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:23:25',
                'updated_at' => '2021-04-20 20:23:25',
            ),
            64 => 
            array (
                'id' => 65,
                'variation_id' => 65,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:23:28',
                'updated_at' => '2021-04-20 20:23:28',
            ),
            65 => 
            array (
                'id' => 66,
                'variation_id' => 66,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:23:33',
                'updated_at' => '2021-04-20 20:23:33',
            ),
            66 => 
            array (
                'id' => 67,
                'variation_id' => 67,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:23:36',
                'updated_at' => '2021-04-20 20:23:36',
            ),
            67 => 
            array (
                'id' => 68,
                'variation_id' => 68,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:23:40',
                'updated_at' => '2021-04-20 20:23:40',
            ),
            68 => 
            array (
                'id' => 69,
                'variation_id' => 69,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:23:43',
                'updated_at' => '2021-04-20 20:23:43',
            ),
            69 => 
            array (
                'id' => 70,
                'variation_id' => 70,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:23:46',
                'updated_at' => '2021-04-20 20:23:46',
            ),
            70 => 
            array (
                'id' => 71,
                'variation_id' => 71,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:23:50',
                'updated_at' => '2021-04-20 20:23:50',
            ),
            71 => 
            array (
                'id' => 72,
                'variation_id' => 72,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:23:53',
                'updated_at' => '2021-04-20 20:23:53',
            ),
            72 => 
            array (
                'id' => 73,
                'variation_id' => 73,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:23:56',
                'updated_at' => '2021-04-20 20:23:56',
            ),
            73 => 
            array (
                'id' => 74,
                'variation_id' => 74,
                'total_stock' => 3,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:24:02',
                'updated_at' => '2021-04-20 20:24:02',
            ),
            74 => 
            array (
                'id' => 75,
                'variation_id' => 75,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:24:05',
                'updated_at' => '2021-04-20 20:24:05',
            ),
            75 => 
            array (
                'id' => 76,
                'variation_id' => 76,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:24:08',
                'updated_at' => '2021-04-20 20:24:08',
            ),
            76 => 
            array (
                'id' => 77,
                'variation_id' => 77,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:24:11',
                'updated_at' => '2021-04-20 20:24:11',
            ),
            77 => 
            array (
                'id' => 78,
                'variation_id' => 78,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:24:16',
                'updated_at' => '2021-04-20 20:24:16',
            ),
            78 => 
            array (
                'id' => 79,
                'variation_id' => 79,
                'total_stock' => 0,
                'available_quantity_meli' => 0,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:24:23',
                'updated_at' => '2021-04-20 20:24:23',
            ),
            79 => 
            array (
                'id' => 80,
                'variation_id' => 80,
                'total_stock' => 8,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:24:27',
                'updated_at' => '2021-04-20 20:24:27',
            ),
            80 => 
            array (
                'id' => 81,
                'variation_id' => 81,
                'total_stock' => 7,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:24:57',
                'updated_at' => '2021-04-20 20:24:57',
            ),
            81 => 
            array (
                'id' => 82,
                'variation_id' => 82,
                'total_stock' => 11,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:25:29',
                'updated_at' => '2021-04-20 20:25:29',
            ),
            82 => 
            array (
                'id' => 83,
                'variation_id' => 83,
                'total_stock' => 7,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:25:36',
                'updated_at' => '2021-04-20 20:25:36',
            ),
            83 => 
            array (
                'id' => 84,
                'variation_id' => 84,
                'total_stock' => 1,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:25:38',
                'updated_at' => '2021-04-20 20:25:38',
            ),
            84 => 
            array (
                'id' => 85,
                'variation_id' => 85,
                'total_stock' => 10,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:25:46',
                'updated_at' => '2021-04-20 20:25:46',
            ),
            85 => 
            array (
                'id' => 86,
                'variation_id' => 86,
                'total_stock' => 13,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:25:51',
                'updated_at' => '2021-04-20 20:25:51',
            ),
            86 => 
            array (
                'id' => 87,
                'variation_id' => 87,
                'total_stock' => 1,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:25:56',
                'updated_at' => '2021-04-20 20:25:56',
            ),
            87 => 
            array (
                'id' => 88,
                'variation_id' => 88,
                'total_stock' => 1,
                'available_quantity_meli' => 1,
                'published_meli_history' => 0,
                'available_quantity_here' => 1,
                'published_here_history' => 0,
                'sold_on_meli' => 0,
                'sold_on_here' => 0,
                'critical_stock' => 10,
                'created_at' => '2021-04-20 20:25:58',
                'updated_at' => '2021-04-20 20:25:58',
            ),
        ));
        
        
    }
}